FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl libc6-compat ffmpeg

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci
RUN npx prisma generate

COPY . .
RUN npm run build

ENV NODE_ENV=production
ENV PORT=3001
EXPOSE 3001
CMD ["npm", "run", "server:start"]
