/**
 * Shared utilities, types, constants, and components for canvas node components.
 *
 * This file re-exports from ProjectCanvasPage.tsx so that node files have a
 * single import source. The circular dependency (ProjectCanvasPage imports
 * nodeTypes from nodes/index, node files import utils via this barrel) is
 * safe because all re-exported symbols are function declarations or
 * constants that are fully available before any React component renders.
 */
export {
  // Types
  type CanvasNodeProps,
  type CanvasProjectPromptContext,
  type CanvasReferenceImage,
  type CharacterAudioReference,
  type WorkflowAssetKind,
  type WorkflowAssets,
  type WorkflowAssetItem,
  type AssetImagePreview,

  // Constants
  CANVAS_IMAGE_RATIO_OPTIONS,
  CANVAS_GENERATION_STALE_MS,
  CANVAS_TRANSLATION_STALE_MS,
  CANVAS_VIDEO_POLL_INTERVAL_MS,
  CANVAS_VIDEO_POLL_TIMEOUT_MS,
  CANVAS_GENERATION_RECORDS_REFRESH_EVENT,
  WORKFLOW_ASSET_SYNC_EVENT,
  MAX_VIDEO_REFERENCE_IMAGES,
  videoResolutionOptions,
  videoDurationOptions,
  videoRatioOptions,

  // Components
  CanvasNodeResizer,
  CanvasHandle,

  // Utility functions
  publicImageUrl,
  publicAudioUrl,
  previewCanvasImage,
  downloadCanvasImagePreview,
  syncWorkflowAssetsFromCanvas,
  readObjectString,
  positiveNumber,
  ratioToNumber,
  canvasGenerationStartedAt,
  createCanvasGenerationRequestToken,
  canvasGenerationAgeMs,
  isCanvasGenerationStale,
  canvasGenerationWaitLabel,
  shouldKeepCanvasGenerationPendingAfterError,
  appendCanvasImageGenerationRetryHint,
  canvasPromptTooLongError,
  isCanvasPromptWithinApiLimit,
  isDreaminaWebVideoPromptWithinLimit,
  dreaminaWebVideoPromptTooLongError,
  normalizeCanvasImageSize,
  normalizeImageResolution,
  normalizeVideoResolution,
  normalizeVideoDuration,
  normalizeVideoRatio,
  normalizeGenerationCount,
  normalizeWorkflowAssetKind,
  normalizeCompareText,
  modelOptionLabel,
  isWorkflowImageModel,
  isWorkflowTextModel,
  isWorkflowVideoModel,
  isDreaminaWebImageModel,
  formatDurationMs,
  canvasSectionToneClasses,
  canvasNodeEpisodeId,
  canvasNodePromptText,
  canvasNodePromptLabel,
  canvasNodeReferenceUrl,
  translatedPromptPatchForNode,
  compactProjectPromptContext,
  buildCanvasCharacterFinalPrompt,
  buildCanvasAssetFinalPrompt,
  isRawCharacterAssetPrompt,
  isRawAssetPrompt,
  hasManualCanvasGenerationPrompt,
  finalPromptSatisfiesProjectIdentity,
  uploadCanvasReferenceFile,
  canvasVideoProviderFailed,
  canvasVideoResultErrorMessage,
  canvasVideoPollErrorMessage,
  shouldRetryCanvasVideoPollError,
  canvasVideoReferencePreviewMessage,
  isStoryboardReferenceNodeForVideo,
  isStoryboardSlotNodeForVideo,
  videoReferenceSourcePriority,
  videoReferenceLabel,
  characterAudioReferencesFromNodeData,
  mergeVideoAudioReferencesWithIncoming,
  uniqueClipNames,
  generationReferenceSourcePriority,
  shouldSkipCanvasGenerationReference,
  canvasReferenceImageKind,
  canvasReferenceDedupKey,
  canvasReferenceImageBadgeLabel,
  defaultWorkflowAssets,
  assetArray,
  workflowAssetName,
  workflowAssetKindLabel,
  workflowAssetKindSelectLabel,
  mergeWorkflowAssetsWithProjectRecords,
  canvasOutputImageVariantsFromResult,
  recoverCanvasImageFromGenerationRecords,
  findLatestCanvasImageGenerationRecord,
  generationRecordStartedAt,
  appendReferenceImageMapPrompt,
  prepareCanvasPromptForImageModel,
} from '../../../pages/ProjectCanvasPage';
