/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cxrbkmagnmofakxnooxz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4cmJrbWFnbm1vZmFreG5vb3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwMDc4NDgsImV4cCI6MjA5NDU4Mzg0OH0.H9-kUfexXus1JAI4XJuUCx3Csu3iwZ8dWfbPwV-Vfxo"