/**
 * Backward-compatible re-export from the split api/ modules.
 * All consumers that import from '../lib/apiClient' continue to work unchanged.
 */
export { apiClient, API_AUTH_EXPIRED_EVENT } from './api'

export type {
  AgentConversation,
  AgentHistoryMessage,
  AgentSendMessageRequest,
  AgentSendMessageResponse,
  ApiUser,
  CanvasImageGenerationInput,
  CanvasPromptInspectionInput,
  CanvasPromptInspectionResponse,
  CanvasPromptOptimizationInput,
  CanvasPromptOptimizationResponse,
  CanvasPromptTranslationInput,
  CanvasPromptTranslationResponse,
  CanvasScene,
  CanvasVideoGenerationInput,
  CanvasVideoGenerationResponse,
  CharacterReferenceAudioInput,
  CharacterReferenceImageInput,
  CharacterReferenceImageResponse,
  ClearCharacterReferenceAudioInput,
  ClipSeedancePromptResponse,
  ClipStoryboardPlanResponse,
  DraftModelTestInput,
  EpisodeCanvasSyncResponse,
  GenerationRecord,
  GenerationRecordAsset,
  GenerationRecordModel,
  LocalImageUploadResponse,
  ModelConfig,
  ModelConfigInput,
  ModelConfigsResponse,
  ModelProviderConfig,
  PresignedUploadResponse,
  ProjectCharacterAsset,
  ProjectCharacterRecord,
  ProjectSceneRecord,
  ProviderConfigInput,
  ProviderTestResult,
  WorkflowAssetImageGenerationInput,
  WorkflowAssetImageGenerationResponse,
  WorkflowAssetImageHistoryItem,
  WorkflowAssetReferenceImageInput,
  WorkflowBreakdownScene,
  WorkflowClip,
  WorkflowEpisodeListResponse,
  WorkflowEpisodeSummary,
  WorkflowRunResponse,
  WorkflowState,
} from './api'
